language: python
python:
  - "3.9"

before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install coveralls
  - pip install build
  - pip install -r requirements.txt

script:
  - coverage run -m pytest
after_success:
  - coveralls

deploy:
  - provider: script
    script: make package
    on:
      branch: main
  - provider: lambda
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    role: $ROLE_ARN
    region: "us-east-2"
    function_name: "jwstascii-updater"
    module_name: "lambda_function"
    handler_name: "lambda_handler"
    runtime: "python3.9"
    zip: build/jwstascii-lambda-updater.zip
    on:
      branch: main
